#!/bin/bash

# Increase spawn timeout to 1 minute
export JUPYTER_SPAWN_TIMEOUT=60

# Start Jupyter notebook server
jupyter notebook &

# Enable Voila extension
jupyter server extension enable --sys-prefix voila

# Keep the container running
tail -f /dev/null
