#!/bin/bash

# Start Jupyter notebook server
jupyter notebook &

# Wait for 2 minutes to allow the server to start up
sleep 120

# Enable Voila extension
jupyter server extension enable --sys-prefix voila

# Keep the container running
tail -f /dev/null
